### ISSUE TITLE
Pull in `structopt` sub-command name fix when it lands.

### ISSUE THREAD

**Issue by nathan-at-least** [cargo-checkmate/cargo-checkmate#27]
The `structopt` issue is here: https://github.com/TeXitoi/structopt/issues/391

Current workaround merged in https://github.com/nathan-at-least/cargo-checkmate/pull/26

**Comment by zancas** [comment]
I notice that `clap` passes `checkmate` but `structopt` does not.   Combined with the deprecatio of `structopt`..   doesn't this argue for refactoring `checkmate` to depend on `clap` instead of `structopt`?

**Comment by nathan-at-least** [comment]
Oh nice! I didn't notice `clap` did that. Filed https://github.com/cargo-checkmate/cargo-checkmate/issues/32 .

**Comment by nathan-at-least** [comment]
We moved away from `structopt` in #40 released in [v0.1.12](https://github.com/cargo-checkmate/cargo-checkmate/releases/tag/v0.1.12).
